name: Cache demo
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ${CACHE_PATH}
          # Use a unique cache key to ensure the cache is always missed, so its
          # cache save `post` step is always triggered.
          key: run-${{ github.run_id }}:attempt-${{ github.run_attempt }}
        env:
          # Use a dummy file which already exists.
          CACHE_PATH: /etc/hosts
